### PR TITLE
Updating to latest versions of dependencies

### LINKED ISSUE #25: No longer supports nesting since 2.0.3
Since extension was updated to 2.0.3 `/**/` comments now work as expected, but all nested rules are now being marked as errors. Is it possible this has something to do with the update or did I do anything wrong? Previously I had no problems with nested styles. Thanks!

screenshot-postcss

### PR DESCRIPTION
**Pull request by baohouse**
Updating package dependencies to resolve #25 

I tested it by taking version 2.0.2's VSIX file, unzipping it, replacing the extensions folder with the updated compiled code, rezip and rename to a VSIX file, and then installed it into Visual Studio Code 1.21.1, and it looked like it work. Could use another tester though!

### CODE REVIEW

**Comment by aldebaran798** [comment]
@MhMadHamster please merge this. Thanks

**Comment by MhMadHamster** [comment]
why this pr removes package.json from server?

**Comment by baohouse** [comment]
@MhMadHamster The /server/package.json is consolidated to /package.json. The compile script is in the /package.json. I suppose if you intended that the server be a separate sub-package with its own compile script, I can split it back out again.

**Comment by baohouse** [comment]
I'm posting a build version here for folks wanting to help me test it. I tested it on some PCSS files, and it looks okay, but more testing would be helpful, especially comparing it against version 2.0.2. Just unzip the file (so you should get a file with *.vsix extension) and install into Visual Studio Code.

[vscode-postcss-language-2.1.0-rc1.vsix.zip](https://github.com/MhMadHamster/vscode-postcss-language/files/1870520/vscode-postcss-language-2.1.0-rc1.vsix.zip)

**Comment by MhMadHamster** [comment]
i checked it locally seems ok

**Comment by MhMadHamster** [comment]
published

**Pull request merged**
